package research.fcl.webapp.endpoints;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import research.fcl.library.Application;
import research.fcl.webapp.endpoints.dto.DefaultGsonMapper;
import research.fcl.webapp.endpoints.mapper.tree.JsTreeNode;
import research.fcl.webapp.endpoints.mapper.tree.JsTreeNodeMapper;

/**
 * Endpoint that provides JSON data for jsTree
 *  in format :
 *  {
{
  id          : "string" // will be autogenerated if omitted
  text        : "string" // node text
  icon        : "string" // string for custom
  state       : {
    opened    : boolean  // is the node open
    disabled  : boolean  // is the node disabled
    selected  : boolean  // is the node selected
  },
  children    : []  // array of strings or objects
  li_attr     : {}  // attributes for the generated LI node
  a_attr      : {}  // attributes for the generated A node
}
}
 * @author vilgefortz
 *
 */
public class Tree {
	public static String getTreeData(HttpServletRequest request,
			HttpServletResponse response, Application app) {
			DefaultGsonMapper mapper = new DefaultGsonMapper(mapApplication (app));
			try {
				return mapper.toJson();
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		return "[{ \"text\":\"no data available\" }]";
	}

	private static Object mapApplication(Application app) {
		JsTreeNodeMapper mapper = new JsTreeNodeMapper ();
		return mapper.map(app);
	}

	
}
